### ISSUE TITLE
No longer working due to authorization mechanism

### ISSUE THREAD

**Issue by ctrevorrow** [z-x/amazon-s3-direct-post-upload#1]
Amazon now requires AWS4-HMAC-SHA256 for the authorization mechanism.

**Comment by campsoftware** [comment]
I just tested a web app I have running and it worked. Has the new authorization rolled out yet?

**Comment by ctrevorrow** [comment]
I’m not sure on the specific dates, but I believe all new S3 buckets only allow v4 now.  If you create a new bucket and try it on that one, I expect it will give you the error.  My bucket is in us-east-2 (Ohio), but I believe this is relevant across all regions.  I’ve spent a good chunk of the day trying to get an upload form working to no avail.  The v4 auth seems a whole lot harder to work with.

**Comment by ctrevorrow** [comment]
As it turns out, on us-east-1 (Virginia), even a new bucket will work using the v2 auth method seen here.  There is only an issue with buckets in newer regions, such as us-east-2 (Ohio).
